version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: docker/production/app/Dockerfile
    working_dir: /var/www
    links:
      - database
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  web:
    build:
      dockerfile: docker/production/web/Dockerfile
    ports:
      - 80:9000



